application:
    host: 0.0.0.0

database:
    require_ssl: true

email_client:
    base_url: "https://api.postmarkapp.com"
    # Use the single sender email you authorised on Postmark!
    sender_email: "something@gmail.com
